site_name: HTTPCore
site_description: A minimal HTTP client for Python.
site_url: https://www.encode.io/httpcore/

repo_name: encode/httpcore
repo_url: https://github.com/encode/httpcore/

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - Connection Pools: 'connection-pools.md'
    - Proxies: 'proxies.md'
    - HTTP/2: 'http2.md'
    - Extensions: 'extensions.md'
    - Async Support: 'async.md'
    - Exceptions: 'exceptions.md'

theme:
  name: "material"

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        watch:
            - httpcore
        handlers:
            python:
                members_order:
                    - "source"

markdown_extensions:
  - codehilite:
      css_class: highlight
